In [5]:
#stack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)
               

[[1 4]
 [2 5]
 [3 6]]


In [7]:
#array split
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [25]:
#hstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [11]:
#splitting 2d array
import numpy as np
arr=np.array([[1,2,3,4],[5,8,9,1],[2,4,5,7]])
newarr=np.split(arr,3)
newarr

[array([[1, 2, 3, 4]]), array([[5, 8, 9, 1]]), array([[2, 4, 5, 7]])]

In [15]:
#hsplit 2d array
import numpy as np
arr=np.array([[1,2,3,4],[5,8,9,1],[2,4,5,7]])
newarr=np.hsplit(arr,2)
newarr

[array([[1, 2],
        [5, 8],
        [2, 4]]),
 array([[3, 4],
        [9, 1],
        [5, 7]])]

In [17]:
#vsplit 2d array
import numpy as np
arr=np.array([[1,2,3,4],[5,8,9,1],[2,4,5,7]])
newarr=np.vsplit(arr,3)
newarr

[array([[1, 2, 3, 4]]), array([[5, 8, 9, 1]]), array([[2, 4, 5, 7]])]

In [43]:
import numpy linalg as LA 
A = np.array([[1,2,3],[3,2,1],[1,0,-1]]) 
w, v = LA.eig(A) 
print(w) 


SyntaxError: invalid syntax (3451506581.py, line 1)